replicaCount: 1

image:
  repository: us-central1-docker.pkg.dev/codetokloud/payment
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 80

resources: {} 

env:
  PAYMENT_GATEWAY_URL: "https://example-gateway.com"
