apiVersion: v1
kind: Service
metadata:
  name: {{ include "<.Chart.Name>.fullname" . }}
spec:
  type: {{ .Values.service.type }}
  selector:
    app: {{ include "<.Chart.Name>.name" . }}
  ports:
  - port: {{ .Values.service.port }}
    targetPort: 8000  
