version: 2.1

parameters:
  run-auth-workflow:
    type: boolean
    default: false
  run-payment-workflow:
    type: boolean
    default: false
  run-search-workflow:
    type: boolean
    default: false

workflows:
  auth-workflow:
    when: << pipeline.parameters.run-auth-workflow >>
    jobs:
      - auth/auth_build
      - auth/auth_deploy

  payment-workflow:
    when: << pipeline.parameters.run-payment-workflow >>
    jobs:
      - payment/payment_build
      - payment/payment_deploy

  search-workflow:
    when: << pipeline.parameters.run-search-workflow >>
    jobs:
      - search/search_build
      - search/search_deploy