version: 2.1

workflows:
  service-deployments:
    jobs:
      - auth_build_and_deploy:
          filters:
            branches:
              only: main
          when: << pipeline.parameters.auth_build_and_deploy >>

      - payment_build_and_deploy:
          filters:
            branches:
              only: main
          when: << pipeline.parameters.payment_build_and_deploy >>

      - search_build_and_deploy:
          filters:
            branches:
              only: main
          when: << pipeline.parameters.search_build_and_deploy >>
