version: 2.1

parameters:
  run-auth-workflow:
    type: boolean
    default: false
  run-payment-workflow:
    type: boolean
    default: false
  run-search-workflow:
    type: boolean
    default: false

workflows:
  auth-workflow:
    when: << pipeline.parameters.run-auth-workflow >>
    jobs:
      - continuation/continue:
          configuration_path: auth/.circleci/config.yml

  payment-workflow:
    when: << pipeline.parameters.run-payment-workflow >>
    jobs:
      - continuation/continue:
          configuration_path: payment/.circleci/config.yml

  search-workflow:
    when: << pipeline.parameters.run-search-workflow >>
    jobs:
      - continuation/continue:
          configuration_path: search/.circleci/config.yml
