version: 2.1

workflows:
  service-deployments:
    jobs:
      - auth_build_and_deploy:
          filters:
            branches:
              only: main

      - payment_build_and_deploy:
          filters:
            branches:
              only: main

      - search_build_and_deploy:
          filters:
            branches:
              only: main
