version: 2.1

workflows:
  service-deployments:
    jobs:
      - auth-deploy:
          filters:
            branches:
              only: main
      - payment-deploy:
          filters:
            branches:
              only: main
      - search-deploy:
          filters:
            branches:
              only: main
