version: 2.1

parameters:
  run-auth-workflow:
    type: boolean
    default: false
  run-payment-workflow:
    type: boolean
    default: false
  run-search-workflow:
    type: boolean
    default: false

workflows:
  auth-workflow:
    run-auth-build-and-deploy:
    when: << pipeline.parameters.run-auth-workflow >>
    jobs:
      - auth/.circleci/config.yml/auth_build
      - auth/.circleci/config.yml/auth_deploy:
          requires:
            - auth/.circleci/config.yml/auth_build

  payment-workflow:
    when: << pipeline.parameters.run-payment-workflow >>
    jobs:
      - payment/.circleci/config.yml/payment_build
      - payment/.circleci/config.yml/payment_deploy:
          requires:
            - payment/.circleci/config.yml/payment_build

  search-workflow:
    when: << pipeline.parameters.run-search-workflow >>
    jobs:
      - search/.circleci/config.yml/search_build
      - search/.circleci/config.yml/search_deploy:
          requires:
            - search/.circleci/config.yml/search_build
