version: 2.1

parameters:
  run-auth-workflow:
    type: boolean
    default: false
  run-payment-workflow:
    type: boolean
    default: false
  run-search-workflow:
    type: boolean
    default: false

workflows:
  auth-workflow:
    when: << pipeline.parameters.run-auth-workflow >>
    jobs:
      - auth_build
      - auth_deploy:
          requires:
            - auth_build

  payment-workflow:
    when: << pipeline.parameters.run-payment-workflow >>
    jobs:
      - payment_build
      - payment_deploy:
          requires:
            - payment_build

  search-workflow:
    when: << pipeline.parameters.run-search-workflow >>
    jobs:
      - search_build
      - search_deploy:
          requires:
            - search_build
