version: 2.1

parameters:
  run-auth-workflow:
    type: boolean
    default: false
  run-payment-workflow:
    type: boolean
    default: false
  run-search-workflow:
    type: boolean
    default: false

jobs:
  backend-test:
      docker:
        - image: cimg/python:3.8
      steps:
        - checkout
        - python/install-packages:
            pkg-manager: pip
        - run:
            name: Run tests
            command: pytest

workflows:
  auth-workflow:
    when: << pipeline.parameters.run-auth-workflow >>
    jobs:
      - backend-test
  payment-workflow:
    when: << pipeline.parameters.run-payment-workflow >>
    jobs:
      - backend-test

  search-workflow:
    when: << pipeline.parameters.run-search-workflow >>
    jobs:
      - backend-test