apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: auth
  template:
    metadata:
      labels:
        app: auth
    spec:
      containers:
      - name: auth-container
        image: gcr.io/<your-project-id>/auth:latest
        ports:
        - containerPort: 8000
        env:
        - name: AUTH_SECRET
          valueFrom:
            configMapKeyRef:
              name: auth-config
              key: AUTH_SECRET

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: auth-config
data:
  AUTH_SECRET: "supersecretpasword@1"
