apiVersion: v1
kind: Service
metadata:
  name: {{ include "<service-name>.fullname" . }}
spec:
  type: {{ .Values.service.type }}
  selector:
    app: {{ include "<service-name>.name" . }}
  ports:
  - port: {{ .Values.service.port }}
    targetPort: 8000  
