apiVersion: v1
kind: Service
metadata:
  name: {{ include "payment.fullname" . }}
spec:
  type: {{ .Values.service.type }}
  selector:
    app: {{ include "payment.name" . }}
  ports:
  - port: {{ .Values.service.port }}
    targetPort: 8002
