
replicaCount: 1

image:
  repository:  us-central1-docker.pkg.dev/codetokloud/search
  pullPolicy: IfNotPresent
  tag: "latest"

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""



podAnnotations: {}

podLabels: {}

podSecurityContext: {}


service:
  type: ClusterIP
  port: 8000


resources: {}

volumes: []

volumeMounts: []


nodeSelector: {}

tolerations: []

affinity: {}
