apiVersion: v1
kind: Service
metadata:
  name: {{ include "auth.fullname" . }}
spec:
  type: {{ .Values.service.type }}
  selector:
    app: {{ include "auth.name" . }}
  ports:
  - port: {{ .Values.service.port }}
    targetPort: 8000
