version: 2.1

jobs:
  detect_auth_changes:
    docker:
    - image: python:3.9-slim
    steps:
    - checkout
    - run:
        name: Check for Changes in Auth Service
        command: |
          if git diff --name-only origin/main...HEAD | grep -q '^auth/'; then
            echo "Changes detected in auth service."
            echo "true" > /tmp/changes_detected.txt
          else
            echo "No changes in auth service."
            echo "false" > /tmp/changes_detected.txt
            exit 0
          fi
    - persist_to_workspace:
        root: /tmp
        paths:
        - changes_detected.txt
  hold_build:
    docker:
    - image: python:3.9-slim
    type: approval
    steps:
    - attach_workspace:
        at: /tmp
    - run:
        name: Check if Build Should Be Held
        command: |
          if [ "$(cat /tmp/changes_detected.txt)" = "true" ]; then
            echo "Changes detected. Skipping hold."
            exit 0  # Skip hold and continue with build.
          else
            echo "No changes detected. Holding build."
            exit 1  # Trigger hold in CircleCI.
          fi

  auth_build:
    docker:
    - image: google/cloud-sdk
    steps:
    - checkout
    - setup_remote_docker

    - run:
        name: Setup Google Cloud SDK
        command: |
          apt-get install -qq -y gettext
          echo $GCLOUD_SERVICE_KEY > gcloud-service-key.json
          gcloud auth activate-service-account --key-file=gcloud-service-key.json
          ls -l
    - run:
        name: docker gcloud init
        command: |
          gcloud auth configure-docker  us-central1-docker.pkg.dev
    - run:
        name: Build and Push Auth Service
        command: |
          docker build -t us-central1-docker.pkg.dev/codetokloud/auth/auth:latest ./services/auth
          docker push us-central1-docker.pkg.dev/codetokloud/auth/auth:latest
  auth_deploy:
    docker:
    - image: google/cloud-sdk:latest
    steps:
    - checkout
    - run:
        name: Authenticate with GKE
        command: |
          echo $GCLOUD_SERVICE_KEY > gcloud-service-key.json
          gcloud auth activate-service-account --key-file=gcloud-service-key.json
          gcloud config set project codetokloud
          gcloud container clusters get-credentials cluster-1 --zone us-central1
    - run:
        name: Install Helm
        command: |
          curl https://raw.githubusercontent.com/helm/helm/master/scripts/get-helm-3 | bash


    - run:
        name: Deploy Auth Service
        command: |
          helm upgrade --install auth ./helm/auth --set image.repository=us-central1-docker.pkg.dev/codetokloud/auth/auth:latest --set image.tag=latest


workflows:
  version: 2
  auth_build_and_deploy:
    jobs:
    - detect_auth_changes
    - hold_build:
        requires:
        - detect_auth_changes
    - auth_build:
        requires:
        - hold_build
    - auth_deploy:
        requires:
        - auth_build
        filters:
          branches:
            only: main
